default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production
