default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: <%= ENV['DATA_DB_HOST'] %>
  username: <%= ENV['DATA_DB_USER'] %>
  password: <%= ENV['DATA_DB_PASS'] %>

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production
